# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa07a7e340f7fe622939a9931b12c2c6cd74b9534ce60df20122614f6a95984475664d92c351a3d83822c72933b573e4926f7ff1b2f1621323a91af8002a435

test:
  secret_key_base: 6913edf62d2e3be1bc6e46778d677f8f0e7f67ab3f5bfb2cc7e7cb2984067745dfc526c78bfeba6b63855dd2f55508d9c983d0412164c21d5329396696f8ee31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
